[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ml_object_detector"
version = "0.1.0"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
