# base_dir: .. # Legacy path, not used in the src-layout structure
input_dir: data/raw
output_dir: data/processed
model_dir: src/ml_object_detector/models/weights
model_name: yolov8n.pt
logs_dir: logs
confidence_threshold: 0.8
template_dir: src/ml_object_detector/postprocess/templates
reports_dir: reports
uploads_dir: uploads
static_dir: static
file_inspection:
  allowed_mime:
    - image/jpeg
    - image/png
    - image/webp
  hard_limit_mb: 10   # absolute hard stop (uploads > this are rejected)
  soft_limit_mb: 5    # optional, require confirmation above this size
