# base_dir: .. # Legacy path, not used in the src-layout structure
input_dir: data/raw
output_dir: data/processed
model_dir: src/ml_object_detector/models/weights
model_name: yolov8n.pt
logs_dir: logs
confidence_threshold: 0.8
template_dir: src/ml_object_detector/postprocess/templates
reports_dir: reports
uploads_dir: uploads
static_dir: static
